basic.showString("Hello!")
basic.showIcon(IconNames.Heart)
music.playMelody("G A B C5 B A B G ", 120)
music.playSoundEffect(music.builtinSoundEffect(soundExpression.hello), SoundExpressionPlayMode.UntilDone)
basic.pause(5000)
music.playSoundEffect(music.builtinSoundEffect(soundExpression.giggle), SoundExpressionPlayMode.UntilDone)
basic.pause(5000)
basic.pause(5000)
music.playSoundEffect(music.builtinSoundEffect(soundExpression.spring), SoundExpressionPlayMode.UntilDone)
music.playMelody("G B A G C5 B A B ", 144)
music.playSoundEffect(music.builtinSoundEffect(soundExpression.slide), SoundExpressionPlayMode.UntilDone)
music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(880, music.beat(BeatFraction.Whole))
music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(659, music.beat(BeatFraction.Whole))
basic.pause(1500)
music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(880, music.beat(BeatFraction.Whole))
music.playTone(659, music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Whole))
basic.pause(500)
music.playTone(587, music.beat(BeatFraction.Whole))
music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Whole))
basic.pause(1500)
music.playTone(587, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(880, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(784, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(587, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(880, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(784, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(698, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(587, music.beat(BeatFraction.Whole))
basic.pause(500)
basic.forever(function () {
	
})
