music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(880, music.beat(BeatFraction.Whole))
music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(659, music.beat(BeatFraction.Whole))
basic.pause(1500)
music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(880, music.beat(BeatFraction.Whole))
music.playTone(659, music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Whole))
basic.pause(500)
music.playTone(587, music.beat(BeatFraction.Whole))
music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Whole))
basic.pause(1500)
music.playTone(587, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(880, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(784, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(587, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(880, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(784, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(698, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(587, music.beat(BeatFraction.Whole))
basic.pause(500)
basic.forever(function () {
	
})
