basic.showString("Hello!")
basic.showIcon(IconNames.Heart)
music.playSoundEffect(music.builtinSoundEffect(soundExpression.hello), SoundExpressionPlayMode.UntilDone)
basic.pause(5000)
music.playSoundEffect(music.builtinSoundEffect(soundExpression.giggle), SoundExpressionPlayMode.UntilDone)
basic.pause(5000)
basic.pause(5000)
music.playSoundEffect(music.builtinSoundEffect(soundExpression.spring), SoundExpressionPlayMode.UntilDone)
music.playMelody("G B A G C5 B A B ", 144)
music.playSoundEffect(music.builtinSoundEffect(soundExpression.slide), SoundExpressionPlayMode.UntilDone)
music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(880, music.beat(BeatFraction.Whole))
music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(659, music.beat(BeatFraction.Whole))
basic.pause(1000)
music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(880, music.beat(BeatFraction.Whole))
music.playTone(659, music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Whole))
basic.pause(1000)
music.playTone(587, music.beat(BeatFraction.Whole))
music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Whole))
basic.pause(1000)
basic.pause(750)
music.playTone(587, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(880, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(784, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(587, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(880, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(784, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(698, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(587, music.beat(BeatFraction.Whole))
basic.pause(1000)
music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(784, music.beat(BeatFraction.Whole))
music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(659, music.beat(BeatFraction.Whole))
basic.pause(1000)
music.playTone(659, music.beat(BeatFraction.Whole))
music.playTone(784, music.beat(BeatFraction.Whole))
music.playTone(659, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Whole))
basic.pause(1000)
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(659, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(466, music.beat(BeatFraction.Whole))
basic.pause(1000)
music.playTone(440, music.beat(BeatFraction.Whole))
music.playTone(494, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Half))
music.playTone(659, music.beat(BeatFraction.Half))
basic.pause(500)
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Whole))
music.playTone(659, music.beat(BeatFraction.Whole))
basic.pause(10000)
basic.pause(5000)
music.playTone(494, music.beat(BeatFraction.Whole))
music.playTone(659, music.beat(BeatFraction.Whole))
music.playTone(784, music.beat(BeatFraction.Half))
music.playTone(740, music.beat(BeatFraction.Half))
music.playTone(659, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(988, music.beat(BeatFraction.Whole))
music.playTone(880, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(740, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(659, music.beat(BeatFraction.Whole))
music.playTone(784, music.beat(BeatFraction.Half))
music.playTone(740, music.beat(BeatFraction.Half))
music.playTone(622, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(659, music.beat(BeatFraction.Whole))
music.playTone(494, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(494, music.beat(BeatFraction.Whole))
music.playTone(659, music.beat(BeatFraction.Whole))
music.playTone(784, music.beat(BeatFraction.Half))
music.playTone(740, music.beat(BeatFraction.Half))
music.playTone(659, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(988, music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Whole))
music.playTone(554, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(831, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(988, music.beat(BeatFraction.Half))
music.playTone(932, music.beat(BeatFraction.Half))
music.playTone(466, music.beat(BeatFraction.Whole))
music.playTone(784, music.beat(BeatFraction.Whole))
music.playTone(659, music.beat(BeatFraction.Whole))
